# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ARENA Documentation
email: "info@conix.io"
github_username: conix-center
description: Tutorials and Reference for the ARENA project.
baseurl: "/ARENA"
url: https://conix-center.github.io
aux_links:
  "The ARENA":
    - "https://arena.andrew.cmu.edu/"
  "CONIX Research Center":
    - "https://conix.io/arena"
  "Our GitHub":
    - "https://github.com/conix-center/"
footer_content: "Copyright &copy; 2020, CONIX Research Center"

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..3
logo: /favicon.ico

#theme: just-the-docs
# after github-pages, change to:
remote_theme: conix-center/just-the-docs

defaults:
  - scope: {path: "content"}
    values:
      layout: default

include:
 - assets
 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Rakefile
  - vendor
